"""Contract constants linking this implementation to the governing architecture."""

IMPLEMENTED_SYSTEM_ID = "SYS-001"
ARCHITECTURE_REPO = "spectrum-systems"
SPEC_VERSION = "1.0.0"
SCHEMA_VERSION = "1.0.0"
PROVENANCE_GUIDANCE_VERSION = "1.0.0"
ERROR_TAXONOMY_VERSION = "1.0.0"
IMPLEMENTATION_REPO = "comment-resolution-engine"
DEFAULT_WORKFLOW_NAME = "NTIA Comment Resolution Pipeline"
DEFAULT_WORKFLOW_STEP = "generate_outputs"
DEFAULT_GENERATION_MODE = "DETERMINISTIC_PIPELINE"
